name: pull-request-to-main
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build and test
        run: ./gradlew check
      - name: Generate reports
        run: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
          name: codecov