name: pull-request-to-main
on:
  push:
    branches:
      - github-actions
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '9']
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build and test
        run: ./gradlew check
      - name: Jacoco and Coveralls
        run: ./gradlew jacocoTestReport coveralls