name: Unit tests and Coverage
on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - combined-sdk
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.java }} (${{ matrix.distribution }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build and test
        run: ./gradlew check --stacktrace
      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport --stacktrace
      - name: Upload coverage to Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew cjacocoTestReport overallsJacoco --stacktrace
